# Generated by Django 4.2.11 on 2025-02-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blogpost_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
